import dbQuery from '@/lib/dbQuery';

export async function getPrecios() {
  const query = `SELECT A.ID_FRACCIONAMIENTO,A.FRACCIONAMIENTO,D.TIPO_TERRENO,D.ID_TIPO_TERRENO--,E.PRECIOM2 
		,(SELECT PRECIO_M2 FROM LISTA_PRECIOS WHERE ID_FRACCIONAMIENTO=A.ID_FRACCIONAMIENTO AND ID_TIPO_TERRENO=D.ID_TIPO_TERRENO) AS PRECIO_M2
        FROM CAT_FRACCIONAMIENTOS A
        INNER JOIN CAT_MANZANAS B ON A.ID_FRACCIONAMIENTO=B.ID_FRACCIONAMIENTO
        INNER JOIN CAT_TERRENOS C ON B.ID_MANZANA=C.ID_MANZANA
        INNER JOIN CAT_TIPOS_TERRENO D ON C.TIPO_TERRENO=D.ID_TIPO_TERRENO
       -- INNER JOIN LISTA_PRECIOS E ON A.ID_FRACCIONAMIENTO = E.IDFRACCIONAMIENTO
        WHERE D.ID_TIPO_TERRENO IN (1,10,13,15)
        GROUP BY A.ID_FRACCIONAMIENTO,A.FRACCIONAMIENTO,D.TIPO_TERRENO,D.ID_TIPO_TERRENO --,E.PRECIOM2 
		ORDER BY A.ID_FRACCIONAMIENTO ASC`;
  const { rows } = await dbQuery(query);
  return rows;
}
