import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import next from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Grupo Lotificadora",
  description: "Generated by Hexcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
