import type { Metadata } from "next";
import "./landing.css";

export const metadata: Metadata = {
  title: "Grupo Lotificadora",
  description: "Generated by Hexcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bodyLanding">{children}</body>
    </html>
  );
}
